version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-'true'}
      - HOST=${HOST:-'0.0.0.0'}
      - PORT=${PORT:-8000}
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - fastapi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 100s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  fastapi-network:
    driver: bridge
